version: "3.8"
services:
  message_board:
    image: eu.gcr.io/message-board-293714/message-board_image

    #    build: .
    #    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"
    volumes:
      - message-board-persistent_data:/home/message-board/persistent_data
volumes:
  message-board-persistent_data:
    driver: local # telling docker to create physical storage in
                  # a local file-system (on current mounted file-system
                  #where docker-compose has been run)