# Generated by Django 3.1.1 on 2020-09-29 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_cur', models.CharField(choices=[('USD', 'USD'), ('CNY', 'CNY'), ('JPY', 'JPY'), ('HKD', 'HKD'), ('MYR', 'MYR'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=3)),
                ('img', models.FilePathField(path='user_management/static/images')),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
