# Generated by Django 3.1.1 on 2020-09-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_management', '0003_auto_20200930_2355'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fav_cur',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='currency_management.currency'),
        ),
    ]
