# Generated by Django 3.1.2 on 2020-12-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200930_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_currency',
        ),
    ]
