# Generated by Django 3.1.1 on 2020-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(choices=[('USD', 'United States Dollar'), ('CNY', 'Canadian Dollar'), ('JPY', 'Japaneses Yen'), ('GBP', 'Great Briton Pound'), ('EUR', 'Euro')], max_length=3)),
                ('value', models.FloatField()),
            ],
        ),
    ]
