# Generated by Django 3.1.1 on 2020-09-30 09:22

from django.db import migrations
from django.apps import apps as app_config


def load_init_cur_val(apps, schema_editor):
    cur_model = apps.get_model("currency_management", "Currency")
    for cur in app_config.get_app_config('currency_management').CURRENCIES:
        init_cur_val = cur_model(currency_name=cur[0], value=cur[2])
        init_cur_val.save()


class Migration(migrations.Migration):
    dependencies = [
        ('currency_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_init_cur_val),

    ]
